apiVersion: batch/v1
kind: CronJob
metadata:
  name: research-scheduler
  namespace: research-copilot
  labels:
    component: scheduler
    job-type: research
spec:
  # Run weekly on Sundays at 6:00 AM UTC
  schedule: "0 6 * * 0"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 3600
  suspend: false
  jobTemplate:
    metadata:
      labels:
        component: job
        job-type: research
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 7200  # 2 hours timeout
      ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
      template:
        metadata:
          labels:
            component: job
            job-type: research
        spec:
          serviceAccountName: research-copilot
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: research-job
            image: research-copilot
            imagePullPolicy: Always
            command:
            - python
            - -m
            - src.agent.main
            args:
            - $(RESEARCH_CONFIG)
            env:
            # Default to LLM research template
            - name: RESEARCH_CONFIG
              value: "llm-research-template"
            # LLM Configuration
            - name: LLM_URL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LLM_URL
            - name: LLM_MODEL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LLM_MODEL
            # Application Configuration
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LOG_LEVEL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: ENVIRONMENT
            - name: CONFIG_DIR
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: CONFIG_DIR
            # Kubernetes Configuration
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # API Credentials
            - name: NOTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: notion-token
            - name: NOTION_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: notion-database-id
            - name: SERPAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: serpapi-key
                  optional: true
            - name: BING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: bing-api-key
                  optional: true
            - name: BING_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: bing-endpoint
                  optional: true
            # Additional environment variables
            envFrom:
            - configMapRef:
                name: research-copilot-config
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: config-templates
              mountPath: /app/config/templates
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/cache
          volumes:
          - name: config-templates
            projected:
              sources:
              - configMap:
                  name: tech-research-template
                  optional: true
              - configMap:
                  name: market-research-template
                  optional: true
              - configMap:
                  name: llm-research-template
                  optional: true
          - name: tmp
            emptyDir:
              sizeLimit: 100Mi
          - name: cache
            emptyDir:
              sizeLimit: 500Mi
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst

---
# Additional CronJob for technology research (monthly)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tech-research-scheduler
  namespace: research-copilot
  labels:
    component: scheduler
    job-type: tech-research
spec:
  # Run monthly on the 1st at 8:00 AM UTC
  schedule: "0 8 1 * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  startingDeadlineSeconds: 3600
  suspend: false
  jobTemplate:
    metadata:
      labels:
        component: job
        job-type: tech-research
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 7200
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            component: job
            job-type: tech-research
        spec:
          serviceAccountName: research-copilot
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: tech-research-job
            image: research-copilot
            imagePullPolicy: Always
            command:
            - python
            - -m
            - src.agent.main
            args:
            - "tech-research-template"
            env:
            # LLM Configuration
            - name: LLM_URL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LLM_URL
            - name: LLM_MODEL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LLM_MODEL
            # Application Configuration
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: LOG_LEVEL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: ENVIRONMENT
            - name: CONFIG_DIR
              valueFrom:
                configMapKeyRef:
                  name: research-copilot-config
                  key: CONFIG_DIR
            # Kubernetes Configuration
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # API Credentials
            - name: NOTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: notion-token
            - name: NOTION_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: notion-database-id
            - name: SERPAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: serpapi-key
                  optional: true
            - name: BING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: bing-api-key
                  optional: true
            - name: BING_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: bing-endpoint
                  optional: true
            # Additional environment variables
            envFrom:
            - configMapRef:
                name: research-copilot-config
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: config-templates
              mountPath: /app/config/templates
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/cache
          volumes:
          - name: config-templates
            projected:
              sources:
              - configMap:
                  name: tech-research-template
                  optional: true
              - configMap:
                  name: market-research-template
                  optional: true
              - configMap:
                  name: llm-research-template
                  optional: true
          - name: tmp
            emptyDir:
              sizeLimit: 100Mi
          - name: cache
            emptyDir:
              sizeLimit: 500Mi
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
