apiVersion: v1
kind: Service
metadata:
  name: research-copilot-service
  namespace: research-copilot
  labels:
    component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    component: agent
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
