apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: research-copilot-production
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

labels:
  - pairs:
      environment: production

images:
  - name: research-copilot
    newName: localhost:5000/research-copilot
    newTag: latest

replicas:
  - name: research-copilot
    count: 1

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: cronjob-patch.yaml
