apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: research-copilot-development
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../base

namePrefix: dev-
nameSuffix: ""

labels:
  - pairs:
      environment: development

images:
  - name: research-copilot
    newName: localhost:5000/research-copilot
    newTag: dev

replicas:
  - name: research-copilot
    count: 1

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
