apiVersion: v1
kind: Secret
metadata:
  name: llm-release-radar-secrets
  namespace: agents
  labels:
    app: llm-release-radar
    component: secrets
type: Opaque
stringData:
  # Notion API Configuration
  NOTION_TOKEN: "secret_your_notion_integration_token_here"
  NOTION_DATABASE_ID: "your_notion_database_id_here"
  NOTION_PAGE_SIZE: "100"
  NOTION_TIMEOUT: "30"
  
  # Search API Configuration
  SEARCH_API_KEY: "your_search_api_key_here"
  
  # Additional secrets can be added here
  # Remember to update these with actual values before deployment
