apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-release-radar
  namespace: agents
  labels:
    app: llm-release-radar
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: agents
  name: llm-release-radar-role
  labels:
    app: llm-release-radar
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-release-radar-rolebinding
  namespace: agents
  labels:
    app: llm-release-radar
    component: rbac
subjects:
- kind: ServiceAccount
  name: llm-release-radar
  namespace: agents
roleRef:
  kind: Role
  name: llm-release-radar-role
  apiGroup: rbac.authorization.k8s.io
