apiVersion: v1
kind: Service
metadata:
  name: llm-release-radar-service
  namespace: agents
  labels:
    app: llm-release-radar
    component: service
spec:
  selector:
    app: llm-release-radar
    component: agent
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  type: ClusterIP
