apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-scraper
spec:
  template:
    spec:
      containers:
      - name: data-scraper
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: VERBOSE
          value: "false"


